import { writeTextFile } from "../shared/fs-utils";
import { RegisteredTool } from "../shared/schemas";

export const taskTools: RegisteredTool[] = [
  {
    name: "tasks.generate_v2_task_plan",
    description: "Generate a v2 hardening task plan from audit results.",
    inputSchema: {
      type: "object",
      properties: {
        goal: { type: "string" },
        auditResults: { type: "object" },
      },
      additionalProperties: true,
    },
    run(input) {
      const audit = JSON.stringify(input.auditResults ?? {});
      return {
        goal: input.goal ?? "pilly-v2-backend-hardening",
        p0: [
          ...(audit.includes("WORFLOWs.md") ? ["Rename WORFLOWs.md to WORKFLOWS.md."] : []),
          "Keep safety boundaries explicit across README, API, and safety docs.",
          "Audit backend function contracts before editing Cloud Functions.",
          "Add required tests for fallback, urgent phrases, medication logs, refusal/help notifications, missed-dose logic, leaving-home, seed data, and rules.",
          "Run available tests and builds and document blockers.",
        ],
        p1: [
          "Document demo verification paths.",
          "Polish README positioning without claiming production readiness.",
          "Document Firestore and Storage rule direction.",
          "Preserve caregiver dashboard visibility for refusal, snooze, missed, and help-request states.",
        ],
        p2: [
          "Improve business direction docs.",
          "Refresh portfolio screenshots.",
          "Document future pilot requirements without implying readiness.",
        ],
        blocked: audit.includes("No test script") || audit.includes("missingTests") ? ["Automated test coverage may require adding a test harness first."] : [],
      };
    },
  },
  {
    name: "tasks.update_tasks_v2",
    description: "Allowed write tool: create or update TASKS_V2.md with current plan and blockers.",
    inputSchema: {
      type: "object",
      properties: {
        status: { type: "string" },
        p0: { type: "array", items: { type: "string" } },
        p1: { type: "array", items: { type: "string" } },
        p2: { type: "array", items: { type: "string" } },
        blockers: { type: "array", items: { type: "string" } },
      },
      additionalProperties: false,
    },
    run(input) {
      const content = renderTasks(input);
      writeTextFile("TASKS_V2.md", content);
      return { written: true, path: "TASKS_V2.md" };
    },
  },
  {
    name: "docs.generate_backend_contract_report",
    description: "Allowed write tool: create or update BACKEND_CONTRACT_AUDIT.md.",
    inputSchema: {
      type: "object",
      properties: {
        summary: { type: "string" },
        functionsFound: { type: "array", items: { type: "string" } },
        missingFunctions: { type: "array", items: { type: "string" } },
        risks: { type: "array", items: { type: "string" } },
        missingTests: { type: "array", items: { type: "string" } },
      },
      additionalProperties: false,
    },
    run(input) {
      const content = [
        "# Backend Contract Audit",
        "",
        String(input.summary ?? "Generated by the repo-local Pilly MCP server."),
        "",
        "## Functions Found",
        bullet(input.functionsFound),
        "",
        "## Missing Functions",
        bullet(input.missingFunctions),
        "",
        "## Firestore Writes And Notification Behavior",
        "Run `pilly.audit_function_contracts` for structured per-function reads, writes, notification behavior, and safety behavior.",
        "",
        "## Safety Behavior",
        "AI must remain limited to bounded response classification and safe workflow routing. Pilly must not provide diagnosis, dosage advice, medication recommendations, emergency triage, or production healthcare claims.",
        "",
        "## Risks",
        bullet(input.risks),
        "",
        "## Missing Tests",
        bullet(input.missingTests),
        "",
      ].join("\n");
      writeTextFile("BACKEND_CONTRACT_AUDIT.md", content);
      return { written: true, path: "BACKEND_CONTRACT_AUDIT.md" };
    },
  },
  {
    name: "docs.generate_safety_report",
    description: "Allowed write tool: create or update SAFETY_AUDIT_REPORT.md.",
    inputSchema: {
      type: "object",
      properties: {
        unsafeClaims: { type: "array", items: { type: "string" } },
        urgentPhraseStatus: { type: "string" },
        familyVoiceBoundaryStatus: { type: "string" },
        securityRisks: { type: "array", items: { type: "string" } },
        productionWarnings: { type: "array", items: { type: "string" } },
      },
      additionalProperties: false,
    },
    run(input) {
      const content = [
        "# Safety Audit Report",
        "",
        "## Unsafe Claims",
        bullet(input.unsafeClaims),
        "",
        "## Urgent Phrase Status",
        String(input.urgentPhraseStatus ?? "Not provided."),
        "",
        "## Trusted Family Voice Boundary Status",
        String(input.familyVoiceBoundaryStatus ?? "Not provided."),
        "",
        "## Firestore And Storage Security Risks",
        bullet(input.securityRisks),
        "",
        "## Production-Readiness Warnings",
        bullet(input.productionWarnings),
        "",
        "Pilly is demo only and not for real patient data. It is not a medical product and does not provide medical advice.",
        "",
      ].join("\n");
      writeTextFile("SAFETY_AUDIT_REPORT.md", content);
      return { written: true, path: "SAFETY_AUDIT_REPORT.md" };
    },
  },
];

function renderTasks(input: Record<string, unknown>): string {
  return [
    "# Pilly v2 Tasks",
    "",
    `Current status: ${String(input.status ?? "Generated by the repo-local Pilly MCP server.")}`,
    "",
    "## P0 Tasks",
    bullet(input.p0),
    "",
    "## P1 Tasks",
    bullet(input.p1),
    "",
    "## P2 Tasks",
    bullet(input.p2),
    "",
    "## Test Checklist",
    "- [ ] Gemini fallback without API key.",
    "- [ ] Urgent phrase static safety guidance.",
    "- [ ] Medication log writes.",
    "- [ ] Refusal notification.",
    "- [ ] Help-request notification.",
    "- [ ] Missed-dose scoping and idempotency.",
    "- [ ] Leaving-home notification.",
    "- [ ] Demo seed data.",
    "- [ ] Firestore household rule documentation or emulator tests.",
    "",
    "## Demo Checklist",
    "- [ ] Golden path.",
    "- [ ] Refusal path.",
    "- [ ] Help-request path.",
    "- [ ] Missed-dose path.",
    "- [ ] Leaving-home path.",
    "- [ ] Trusted Family Voice path.",
    "",
    "## Known Blockers",
    bullet(input.blockers),
    "",
    "## Next Agent Instructions",
    "Run MCP audits before editing: `repo.detect_project_type`, `repo.scan_tree`, `repo.read_key_files`, `pilly.audit_docs`, `pilly.audit_safety_claims`, `pilly.audit_function_contracts`, `pilly.audit_data_model`, `pilly.audit_tests`, `pilly.audit_firestore_rules`, `verify.get_available_scripts`, then generate a task plan.",
    "",
  ].join("\n");
}

function bullet(value: unknown): string {
  const items = Array.isArray(value) ? value : [];
  return items.length ? items.map((item) => `- ${String(item)}`).join("\n") : "- None documented.";
}
